name: example-docker
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'e2e'
          sparse-checkout-cone-mode: false

      - name: Build Docker Image
        run: |
          docker build -t tests .

      - name: Run Tests and Generate Report
        run: |
          docker run --mount type=bind,source="$GITHUB_WORKSPACE",target=/cypress/reports --rm tests sh -c "npm run test:ci"
